New API Proposal - APIUserAccountSpendCount
camaraproject/APIBacklog pull request #120
Opened 2024-11-08 07:04 UTC by wanggz21

New API Proposal - APIQueryTheNumberOfTimesAuserSpendsMoneyOnAnAccount

#### What type of PR is this?

Add one of the following kinds:
* bug
* correction
* enhancement/feature
* cleanup
* documentation
* subproject management
* tests

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for reviewers:

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

2024-11-08 07:26 UTC, wanggz21 commented
Fixes #121

2024-11-10 11:40 UTC, jgarciahospital requested changes

2024-11-10 11:40 UTC, jgarciahospital commented on documentation/API proposals/APIQueryTheNumberOfTimesAuserSpendsMoneyOnAnAccount.md
> +| API family name                           | Query the number of times a user spends money on an account
```suggestion
| API family name                           | UserAccountSpendCount                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |     |
```

2025-06-18 08:47 UTC, albertoramosmonagas commented
Hi @wanggz21 any updates on this issue o new status?

2025-07-09 19:07 UTC, ola1332 approved these changes

2025-07-11 09:15 UTC, jgarciahospital commented
**Proposal marked as Frozen due to inactivity**
 
e.g. 3 missed WG meetings, no updates in 6+ weeks, or no onboarding after TSC approval; related PRs closed and removed from active agenda.
- To reactivate: comment mentioning the proposal owner and notify the WG at least 1 week before the next meeting agenda is finalized; otherwise, it may be archived after 6 months.

2025-07-11 09:15 UTC, closed without merging