new API proposal NetworkHealthAssessment and NetworkTrafficAnalysis
camaraproject/APIBacklog pull request #129
Opened 2024-11-19 08:36 UTC by cnzj-Gc

In reference with issue #127 and #128. contains the material corresponding to the NetworkHealthAssessment and NetworkTrafficAnalysis APl proposal, including the filled-in template and the initial YAML codes

2025-02-27 22:11 UTC, jgarciahospital requested changes

2025-02-27 22:11 UTC, jgarciahospital commented on documentation/API proposals/APIproposal_NetworkHealthAssessment_chinaunicom.md
> +| API summary | This API allows users to query the health score of a 5G private network, which consists of multiple components including the wireless network, transmission network, and core network.
```suggestion
| API summary | This API allows users to query the health score of a given network, which consists of multiple components including the wireless network, transmission network, and core network. By calculating the health score for each component and then applying weighted calculations, the API provides a comprehensive health score result for the given network. |

```

2025-02-27 22:11 UTC, jgarciahospital commented on documentation/API proposals/APIproposal_NetworkTrafficAnalysis_chinaunicom.md
> +| API summary | This API allows users to query statistical information about 5G service traffic for private network customers. Users can select hourly or daily granularity to obtain statistical infor
```suggestion
| API summary | This API allows users to query statistical information about service traffic for a given network's customers. Users can select hourly or daily granularity to obtain statistical information such as uplink and downlink traffic (in MB) and access times for a given network's users, thus monitoring and issuing early warnings for  network quality. |

```

2025-03-04 05:32 UTC, jgarciahospital approved these changes
LGTM

2025-03-04 05:41 UTC, merged

2025-03-05 16:43 UTC, hdamker commented
I have a few questions and issues with this merged proposal:
* formatting: the table is broken (delete the blank lines to repair)
* abbreviation: DPI is used as term, but not explained. Neither what it stands for, nor why and how the technical implementation needs it
* the API has as scope private networks, that should be reflected within the proposal title (as I don't think that it is applicable to public networks in the same way)

2025-03-06 07:36 UTC, cnzj-Gc commented
1、Network traffic analysis relies on Deep Packet Inspection (DPI) because it requires the collection of forwarding data for business traffic within the network to analyze and statistics the concurrent situation of different service requests. The technical principle involves collecting traffic data through User Plane Function (UPF) splitting and switch mirror ports, and then using specialized parsing algorithms to analyze the data, thereby obtaining information such as the number of sessions and upstream and downstream traffic for different services.

2、Network Traffic Analysis (NTA) and Network Health Assessment (NHA) are indeed not suitable for public networks. Public networks are more complex, and general users do not need to concern themselves with the overall condition of public networks.

2025-06-13 18:26 UTC, ola1332 approved these changes