New API proposal-Dedicated Networks
camaraproject/APIBacklog pull request #59
Opened 2024-06-20 11:41 UTC by tlohmar

#### What type of PR is this?
New API Proposal

#### What this PR does / why we need it:

Fixed and Mobile Networks offer the capability of separating devices in different (logical) dedicated networks. 

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for reviewers:

#### Changelog input

```
 release-note

```

#### Additional documentation 

This section can be blank.

```
docs

```

2024-09-16 19:29 UTC, jgarciahospital requested changes
Moving supporters to proper field

2024-09-16 19:29 UTC, jgarciahospital commented on documentation/API proposals/APIproposal_DedicatedNetworks.md
> +| API family owner | Ericsson, Nokia, Telefonica, Vodafone |
```suggestion
| API family owner | Ericsson |
```

2024-09-16 19:29 UTC, jgarciahospital commented on documentation/API proposals/APIproposal_DedicatedNetworks.md
> +| Supporters in API Backlog Working Group |  |
```suggestion
| Supporters in API Backlog Working Group | Nokia, Telefonica, Vodafone |
```

2024-10-01 12:27 UTC, hdamker commented
Could this PR be merged? I'm already creating the repository for it as decided in last TSC.

2024-10-01 12:54 UTC, jgarciahospital approved these changes
LGTM

2024-10-01 13:30 UTC, hdamker commented
@jgarciahospital I would just not close the issue #60 with the PR, as Codeowners and Maintainers are still collected there.

2024-10-09 17:41 UTC, jgarciahospital commented
PR to be merged as API validated in TSC and group created with participants assigned (thanks @tlohmar). @camaraproject/api-backlog_maintainers can anyone review for merging?

2024-10-10 09:28 UTC, hdamker commented
I need the link for the AHC ... therefore I will merge now.

@jgarciahospital Could we agree that API Proposals are merged BEFORE they are brought to the TSC? And do changes after the TSC with new PRs? That would create more transparency.

2024-10-10 09:28 UTC, merged